"use strict";

const crypto = require("node:crypto");
const dgram = require("node:dgram");
const http = require("node:http");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFile } = require("node:child_process");
const { promisify } = require("node:util");
const { now, safeText, PROTOCOL_VERSION } = require("../../shared/protocol");
const exec = promisify(execFile);

const ROOT = path.resolve(__dirname, "..");
const CONFIG = path.join(ROOT, "config", "node.local.json");
const EXAMPLE = path.join(ROOT, "config", "node.example.json");
const IDENTITY = path.join(ROOT, "config", "node.identity.json");
const PUBLIC = path.join(ROOT, "public");
function json(file, fallback) { try { return JSON.parse(fs.readFileSync(file,"utf8")); } catch { return fallback; } }
if (!fs.existsSync(CONFIG)) fs.copyFileSync(EXAMPLE, CONFIG);
const config = json(CONFIG, json(EXAMPLE, {}));
const events = [], conversations = { local:[] }, seenInbox = new Set();
const hub = { url:config.hubUrl || "", name:"", pairing:"not-discovered", lastError:"", lastInboxId:"", lastSeen:"" };
let latest = null, inboxBusy = false;

function log(type,message) { events.unshift({at:now(),type,message:safeText(message,500)});events.splice(120); }
function saveJson(file,value,mode) { fs.writeFileSync(file,JSON.stringify(value,null,2)+"\n",{mode}); try {fs.chmodSync(file,mode);} catch {} }
function identity() { let value=json(IDENTITY,null);if(value?.publicKey&&value?.privateKey)return value;const keys=crypto.generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}});value={publicKey:keys.publicKey,privateKey:keys.privateKey,fingerprint:crypto.createHash("sha256").update(keys.publicKey).digest("hex"),createdAt:now()};saveJson(IDENTITY,value,0o600);log("identity","Created this device's pairing identity");return value; }
const device = identity();
function commandFor(capability,fallback) { const configured=config.commandPaths&&config.commandPaths[capability];return typeof configured==="string"&&configured.trim()?configured.trim():fallback; }
async function probe(command,args=[]) { try {const {stdout}=await exec(command,args,{timeout:6000});return {present:true,output:safeText(stdout,400)};}catch(error){return {present:false,output:safeText(error.code==="ENOENT"?"not installed":error.message,400)};} }
async function collect() { const [nodeVersion,openclaw,hermes,ollama,nvidia]=await Promise.all([probe(process.execPath,["--version"]),probe(commandFor("openclaw","openclaw"),["--version"]),probe(commandFor("hermes","hermes"),["--version"]),probe(commandFor("ollama","ollama"),["list"]),probe(commandFor("nvidia","nvidia-smi"),["--query-gpu=name,utilization.gpu,memory.used,memory.total,temperature.gpu","--format=csv,noheader,nounits"])]);const mem=process.memoryUsage();return {nodeId:config.nodeId,agentName:config.agentName,role:config.role,hostname:os.hostname(),status:"online",at:now(),runtime:{node:nodeVersion.output,uptimeSeconds:Math.round(process.uptime()),memoryMb:Math.round(mem.rss/1024/1024)},capabilities:{openclaw,hermes,ollama,nvidia},events:events.slice(0,20)}; }
function endpoint() { return hub.url || config.hubUrl || ""; }
async function plainFetch(route,options={}) { const base=endpoint();if(!base)throw new Error("Hub not discovered");return fetch(new URL(route,base),options); }
async function signedFetch(route,{method="GET",body}={}) { const raw=body?JSON.stringify(body):"",timestamp=Date.now(),pathname=route.split("?")[0],payload=`${timestamp}\n${method}\n${pathname}\n${raw}`,signature=crypto.sign("sha256",Buffer.from(payload),device.privateKey).toString("base64");const response=await plainFetch(route,{method,headers:{"content-type":"application/json","x-pitt-node":config.nodeId,"x-pitt-time":String(timestamp),"x-pitt-signature":signature},body:raw||undefined,signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`Hub returned ${response.status}`);return response.json(); }
async function pair(snapshot) { if(!endpoint()||!config.nodeId||String(config.nodeId).startsWith("replace-"))return;try{const response=await plainFetch("/api/pair/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nodeId:config.nodeId,agentName:config.agentName,role:config.role,hostname:os.hostname(),capabilities:snapshot.capabilities,publicKey:device.publicKey}),signal:AbortSignal.timeout(12000)});if(!response.ok)throw new Error(`Hub returned ${response.status}`);const result=await response.json();if(hub.pairing!==result.status)log("pairing",result.status==="approved"?"Hub approved this device":"Waiting for Hub approval");hub.pairing=result.status;hub.lastError="";}catch(error){hub.lastError=safeText(error.message,180);hub.pairing="unavailable";} }
async function heartbeat(snapshot) { if(hub.pairing!=="approved")return;try{await signedFetch("/api/nodes/heartbeat",{method:"POST",body:snapshot});hub.lastSeen=now();hub.lastError="";}catch(error){hub.lastError=safeText(error.message,180);if(String(error.message).includes("401"))hub.pairing="not-approved";} }
function addConversation(conversationId,message) { (conversations[conversationId] ||= []).push(message);conversations[conversationId]=conversations[conversationId].slice(-200); }
function extractText(value) { if(typeof value==="string")return safeText(value,4000);if(!value||typeof value!=="object")return "";for(const key of ["text","content","message","response","output","result"]){const found=value[key];if(typeof found==="string"&&found.trim())return safeText(found,4000);if(found&&typeof found==="object"){const nested=extractText(found);if(nested)return nested;}}return ""; }
function adapterConfig() { return config.agentAdapter || {type:"auto",agentId:"main",timeoutSeconds:180}; }
async function askOllama(text,adapter) { try { const tags=await fetch("http://127.0.0.1:11434/api/tags",{signal:AbortSignal.timeout(3000)});if(!tags.ok)throw new Error("Ollama unavailable");const models=(await tags.json()).models||[],model=adapter.ollamaModel||config.ollamaModel||models[0]?.name;if(!model)throw new Error("No Ollama model installed");const response=await fetch("http://127.0.0.1:11434/api/generate",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({model,prompt:`You are ${config.agentName||"a local assistant"}. Reply helpfully and concisely.\n\nUser: ${text}\nAssistant:`,stream:false}),signal:AbortSignal.timeout(Math.max(10,Number(adapter.timeoutSeconds)||180)*1000)});if(!response.ok)throw new Error(`Ollama returned ${response.status}`);return safeText((await response.json()).response||"",4000)||"Ollama returned no text.";}catch(error){return `Local Ollama adapter error: ${safeText(error.message,300)}`;} }
async function askAgent(text,conversationId) { const adapter=adapterConfig(), type=adapter.type||"auto", openclaw=adapter.command||commandFor("openclaw","openclaw");if(type==="disabled")return "This dashboard's agent adapter is disabled.";if(type==="ollama")return askOllama(text,adapter);if(type==="command"){if(!adapter.command||!Array.isArray(adapter.args))return "Custom agent adapter is not configured.";const args=adapter.args.map(arg=>String(arg).replaceAll("{message}",text).replaceAll("{session}",`dashboard:${config.nodeId}:${conversationId}`));try{const {stdout}=await exec(adapter.command,args,{timeout:Math.max(10,Number(adapter.timeoutSeconds)||180)*1000,maxBuffer:1024*1024});return extractText(jsonText(stdout))||safeText(stdout,4000)||"Agent returned no text.";}catch(error){return `Agent adapter error: ${safeText(error.message,300)}`;}}
  if(type!=="auto"&&type!=="openclaw")return "This agent type needs a configured local adapter.";
  try { const {stdout}=await exec(openclaw,["agent","--agent",adapter.agentId||"main","--session-key",`dashboard:${config.nodeId}:${conversationId}`,"--message",text,"--json","--timeout",String(Math.max(10,Number(adapter.timeoutSeconds)||180))],{timeout:(Math.max(10,Number(adapter.timeoutSeconds)||180)+15)*1000,maxBuffer:2*1024*1024});return extractText(jsonText(stdout))||safeText(stdout,4000)||"Agent returned no text.";} catch(error) { const unavailable=error.code==="ENOENT"||String(error.message).includes("ENOENT");return unavailable&&type==="auto"?askOllama(text,adapter):unavailable?"No compatible local OpenClaw adapter was detected. Configure agentAdapter.command if it is installed elsewhere.":`Agent adapter error: ${safeText(error.message,300)}`; }
}
function jsonText(value) { try{return JSON.parse(value);}catch{return value;} }
async function postToHub(text,conversationId) { const message=await signedFetch("/api/node/messages",{method:"POST",body:{text,conversationId}});addConversation(conversationId,message);return message; }
async function pollInbox() { if(inboxBusy||hub.pairing!=="approved")return;inboxBusy=true;try{const suffix=hub.lastInboxId?`?after=${encodeURIComponent(hub.lastInboxId)}`:"";const result=await signedFetch(`/api/node/inbox${suffix}`);for(const message of result.items||[]){if(seenInbox.has(message.id))continue;seenInbox.add(message.id);hub.lastInboxId=message.id;addConversation(message.conversationId,message);log("meeting",`Received ${message.conversationId} message from ${message.from}`);if(message.requiresReply){const reply=await askAgent(message.text,message.conversationId);const response={id:`local-${Date.now()}`,at:now(),from:config.agentName,text:reply,conversationId:message.conversationId,origin:"node"};addConversation(message.conversationId,response);await postToHub(reply,message.conversationId);}}}catch(error){hub.lastError=safeText(error.message,180);}finally{inboxBusy=false;} }
async function refresh() { latest=await collect();await pair(latest);await heartbeat(latest);await pollInbox();return latest; }
function discover() { if(config.discovery?.enabled===false)return;const socket=dgram.createSocket("udp4");socket.on("message",message=>{try{const found=JSON.parse(message.toString("utf8"));if(found.kind!=="PITT_HUB_HERE_V2"||!found.url)return;const changed=hub.url!==found.url;hub.url=found.url;hub.name=found.name||"Pitt Meeting Hub";if(changed)log("discovery",`Found ${hub.name} at ${hub.url}`);}catch{}});socket.bind(()=>{try{socket.setBroadcast(true);}catch{};setInterval(()=>socket.send(Buffer.from("PITT_HUB_DISCOVER_V2"),Number(config.discovery?.port||35100),"255.255.255.255"),5000);socket.send(Buffer.from("PITT_HUB_DISCOVER_V2"),Number(config.discovery?.port||35100),"255.255.255.255");});socket.on("error",error=>log("discovery",`LAN discovery unavailable: ${error.message}`)); }
function send(res,code,data) { res.writeHead(code,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(data)); }
function staticFile(res,urlPath) { const file=urlPath==="/"?"index.html":urlPath.replace(/^\//,"");const candidate=path.resolve(PUBLIC,file);if(!candidate.startsWith(PUBLIC)||!fs.existsSync(candidate)||fs.statSync(candidate).isDirectory())return false;const type={".html":"text/html; charset=utf-8",".css":"text/css; charset=utf-8",".js":"application/javascript"}[path.extname(candidate)]||"application/octet-stream";res.writeHead(200,{"content-type":type,"cache-control":"no-store"});fs.createReadStream(candidate).pipe(res);return true; }
function parseRequest(req) { return new Promise((resolve,reject)=>{let raw="";req.on("data",chunk=>raw+=chunk);req.on("end",()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject(new Error("invalid json"));}});}); }
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);try{if(req.method==="GET"&&url.pathname==="/api/status")return send(res,200,{...(latest||await refresh()),protocol:PROTOCOL_VERSION,hub:{url:endpoint(),name:hub.name,pairing:hub.pairing,lastError:hub.lastError,lastSeen:hub.lastSeen,fingerprint:device.fingerprint}});if(req.method==="POST"&&url.pathname==="/api/refresh")return send(res,200,await refresh());if(req.method==="GET"&&url.pathname==="/api/conversations")return send(res,200,{conversations,hub:{url:endpoint(),pairing:hub.pairing,lastError:hub.lastError}});if(req.method==="POST"&&url.pathname==="/api/chat"){const body=await parseRequest(req),text=safeText(body.text,4000),conversationId=safeText(body.conversationId||"local",120);if(!text)throw new Error("message required");const mine={id:`local-${Date.now()}`,at:now(),from:"Jian",text,conversationId,origin:"local"};addConversation(conversationId,mine);const reply=await askAgent(text,conversationId);const response={id:`local-${Date.now()}-reply`,at:now(),from:config.agentName,text:reply,conversationId,origin:"node"};addConversation(conversationId,response);return send(res,201,{request:mine,response});}if(req.method==="GET"&&staticFile(res,url.pathname))return;send(res,404,{error:"not found"});}catch(error){send(res,400,{error:error.message});}}).listen(config.localPort||3100,"127.0.0.1",()=>{console.log(`Agent Node dashboard listening on http://127.0.0.1:${config.localPort||3100}`);discover();refresh();setInterval(refresh,Math.max(10,Number(config.pollSeconds)||20)*1000);setInterval(pollInbox,3000);});
