"use strict";
// This package intentionally exposes messaging only; it has no local execution path.
const crypto=require("node:crypto"),dgram=require("node:dgram"),http=require("node:http"),fs=require("node:fs"),os=require("node:os"),path=require("node:path");
const {now,safeText,PROTOCOL_VERSION}=require("../../shared/protocol");
const ROOT=path.resolve(__dirname,".."),CONFIG=path.join(ROOT,"config","staff.local.json"),EXAMPLE=path.join(ROOT,"config","staff.example.json"),IDENTITY=path.join(ROOT,"config","staff.identity.json"),PUBLIC=path.join(ROOT,"public");
const json=(file,fallback)=>{try{return JSON.parse(fs.readFileSync(file,"utf8"));}catch{return fallback;}};if(!fs.existsSync(CONFIG))fs.copyFileSync(EXAMPLE,CONFIG);const config=json(CONFIG,json(EXAMPLE,{})),hub={url:config.hubUrl||"",name:"",pairing:"not-registered",lastError:""};let data={participants:[],messages:[]};
function save(file,value,mode){fs.writeFileSync(file,JSON.stringify(value,null,2)+"\n",{mode});try{fs.chmodSync(file,mode);}catch{}}
function identity(){const old=json(IDENTITY,null);if(old?.publicKey&&old?.privateKey)return old;const keys=crypto.generateKeyPairSync("rsa",{modulusLength:2048,publicKeyEncoding:{type:"spki",format:"pem"},privateKeyEncoding:{type:"pkcs8",format:"pem"}}),value={publicKey:keys.publicKey,privateKey:keys.privateKey,fingerprint:crypto.createHash("sha256").update(keys.publicKey).digest("hex"),createdAt:now()};save(IDENTITY,value,0o600);return value;}const device=identity();
function endpoint(){return hub.url||config.hubUrl||"";}async function plain(route,options={}){if(!endpoint())throw new Error("Hub not discovered");return fetch(new URL(route,endpoint()),options);}async function signed(route,{method="GET",body}={}){const raw=body?JSON.stringify(body):"",stamp=Date.now(),pathname=route.split("?")[0],signature=crypto.sign("sha256",Buffer.from(`${stamp}\n${method}\n${pathname}\n${raw}`),device.privateKey).toString("base64"),res=await plain(route,{method,headers:{"content-type":"application/json","x-pitt-node":config.nodeId,"x-pitt-time":String(stamp),"x-pitt-signature":signature},body:raw||undefined,signal:AbortSignal.timeout(10000)});if(!res.ok)throw new Error(`Hub returned ${res.status}`);return res.json();}
async function pair(){if(!endpoint()||!config.nodeId||String(config.nodeId).startsWith("replace-"))throw new Error("Set a unique staff nodeId first");try{const res=await plain("/api/pair/request",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({nodeId:config.nodeId,agentName:config.agentName,role:config.role,hostname:os.hostname(),clientType:"staff",publicKey:device.publicKey,repair:hub.pairing==="not-approved"}),signal:AbortSignal.timeout(10000)});if(!res.ok)throw new Error(`Hub returned ${res.status}`);hub.pairing=(await res.json()).status;hub.lastError="";return hub.pairing;}catch(e){hub.pairing="unavailable";hub.lastError=safeText(e.message,160);throw e;}}
async function refresh(){if(hub.pairing==="pending")await pair();if(hub.pairing!=="approved")return;try{await signed("/api/staff/heartbeat",{method:"POST",body:{nodeId:config.nodeId}});data=await signed("/api/staff/overview");hub.lastError="";}catch(e){hub.lastError=safeText(e.message,160);if(String(e.message).includes("401"))hub.pairing="not-approved";}}
async function checkIn(){await pair();if(hub.pairing==="approved"){await signed("/api/staff/profile",{method:"POST",body:{agentName:config.agentName}});await refresh();}}
async function checkOut(){if(hub.pairing==="approved")await signed("/api/staff/logout",{method:"POST",body:{nodeId:config.nodeId}});hub.pairing="not-registered";hub.lastError="";data={participants:[],messages:[]};}
async function updateProfile(agentName){agentName=safeText(agentName,80);if(!agentName)throw new Error("display name required");config.agentName=agentName;save(CONFIG,config,0o600);if(hub.pairing==="approved")await signed("/api/staff/profile",{method:"POST",body:{agentName}});return agentName;}
function snapshot(){return {...hub,nodeId:config.nodeId,agentName:config.agentName,identity:device.fingerprint,protocol:PROTOCOL_VERSION,participants:data.participants||[],messages:data.messages||[]};}
function discover(){if(config.discovery?.enabled===false)return;const socket=dgram.createSocket("udp4");socket.on("message",msg=>{try{const found=JSON.parse(msg.toString("utf8"));if(found.kind==="PITT_HUB_HERE_V2"&&found.url){hub.url=found.url;hub.name=found.name||"Agents HQ";}}catch{}});socket.bind(()=>{try{socket.setBroadcast(true);}catch{};const send=()=>socket.send(Buffer.from("PITT_HUB_DISCOVER_V2"),Number(config.discovery?.port||35100),"255.255.255.255");send();setInterval(send,5000);});}
function send(res,code,value){res.writeHead(code,{"content-type":"application/json; charset=utf-8","cache-control":"no-store"});res.end(JSON.stringify(value));}function staticFile(res,urlPath){const file=urlPath==="/"?"index.html":urlPath.replace(/^\//,""),candidate=path.resolve(PUBLIC,file);if(!candidate.startsWith(PUBLIC)||!fs.existsSync(candidate)||fs.statSync(candidate).isDirectory())return false;res.writeHead(200,{"content-type":path.extname(candidate)===".js"?"application/javascript":path.extname(candidate)===".css"?"text/css":"text/html; charset=utf-8"});fs.createReadStream(candidate).pipe(res);return true;}function parse(req){return new Promise((resolve,reject)=>{let raw="";req.on("data",c=>raw+=c);req.on("end",()=>{try{resolve(raw?JSON.parse(raw):{});}catch{reject(new Error("invalid json"));}});});}
http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`);try{if(req.method==="GET"&&url.pathname==="/api/status")return send(res,200,snapshot());if(req.method==="POST"&&url.pathname==="/api/refresh"){await refresh();return send(res,200,snapshot());}if(req.method==="POST"&&url.pathname==="/api/register"){await checkIn();return send(res,200,snapshot());}if(req.method==="POST"&&url.pathname==="/api/logout"){await checkOut();return send(res,200,snapshot());}if(req.method==="POST"&&url.pathname==="/api/profile"){const body=await parse(req);await updateProfile(body.agentName);await refresh();return send(res,200,snapshot());}if(req.method==="POST"&&url.pathname==="/api/messages"){if(hub.pairing!=="approved")throw new Error("Check in and wait for Hub approval first");const body=await parse(req),text=safeText(body.text,4000),conversationId=safeText(body.conversationId||"topic:general",120);if(!text)throw new Error("message required");const message=await signed("/api/staff/messages",{method:"POST",body:{text,conversationId}});data.messages=[...(data.messages||[]),message].slice(-400);return send(res,201,message);}if(req.method==="GET"&&staticFile(res,url.pathname))return;send(res,404,{error:"not found"});}catch(e){send(res,400,{error:e.message});}}).listen(config.localPort||3200,"127.0.0.1",()=>{console.log(`Staff Portal listening on http://127.0.0.1:${config.localPort||3200}`);discover();setInterval(()=>refresh().catch(()=>{}),Math.max(5,Number(config.pollSeconds)||10)*1000);});
